### ISSUE TITLE
People page does not work well in IE11.

### ISSUE THREAD

**Issue by avandeursen** [SERG-Delft/serg-delft.github.io#16]
As reported by Hennie Huijgens, the people cards are very narrow in Internet Explorer (e.g. version 11). See below.

Edge, Firefox, Chrome, Safari all seem to work fine.

![image](https://user-images.githubusercontent.com/220701/44053586-64368eee-9f40-11e8-9aaf-6fe842ea646a.png)

**Comment by avandeursen** [comment]
The eventual work around is to add the `d-block` class to each card, _and_ to set the width of the `card-deck` in the style sheet.

Work around inspired by discussion in https://github.com/twbs/bootstrap/issues/21885 (that issue is closed, but the problem has not been solved it seems).

**Comment by snook** [comment]
I added this to CSS rather than adding d-block to each card.

`// if ie10+
@media all and (-ms-high-contrast: none), (-ms-high-contrast: active) {
  // fixes stretched images in cards
  .card-deck .card {
    display: block;
  }

  // fixes stretched images in cards
  .card-group .card {
    display: block;
  }
}`

**Comment by kaydeeweb** [comment]
Hi everyone, I was suffering from this using Bootstrap 4 card deck and IE11. 

Actually card-deck works fine in IE11 if you contain the card-deck into a row and a col. 

So 
      <div class="row">

          <div class="col">

             <div class="card-deck home-page-card-deck text-center">

                      <div class="card mb-4 mb-lg-0">

                            <div class="card-body p-3">
                            <h4 class="card-title"></h4>
                            <p class="card-text"> </p>                      
                            </div>

                       </div> 

                      <div class="card mb-4 mb-lg-0">

                              <div class="card-body p-3">
                              <h4 class="card-title"></h4>
                              <p class="card-text"> </p>                      
                              </div>

                        </div> 

                  </div> 

              </div> 

          </div> 

Working example on [kaydee.net](https://kaydee.net/)

**Comment by abdirahman1104** [comment]
you would rather use card-group instead of card-deck in bootstrap 5 hope that helps.
