### ISSUE TITLE
Link in TU Delft logo

### ISSUE THREAD

**Issue by mauricioaniche** [SERG-Delft/serg-delft.github.io#19]
I suggest we change the link on TU Delft to point to our main/root page.

Right now, it currently points to TU Delft website. It seems ok in a computer as the menu contains a "SERG" option that links back to our main page. However, on mobile, it is more natural to click on the logo, and then, boom, users are out of our website.

**Comment by avandeursen** [comment]
Fixed in 0e76c06d1fb14a6dbf227c743f351dcab3a8e68e
