### ISSUE TITLE
Enable HTTPS

### ISSUE THREAD

**Issue by mardibiase** [SERG-Delft/serg-delft.github.io#20]
Recently Chrome started to mark all non-https websites as "not secure".
Despite the website doesn't handle sensitive data, HTTPS is just a couple of clicks away from the GitHub settings, specifically here: https://help.github.com/articles/securing-your-github-pages-site-with-https/#enforcing-https-for-your-github-pages-site
I can't do that as I am not administrator/owner for the repository.

**Comment by avandeursen** [comment]
Wonderful. I ticked the https box. Thanks!
