### ISSUE TITLE
SERG Reading Club question

### ISSUE THREAD

**Issue by bzz** [SERG-Delft/serg-delft.github.io#66]
Hi 👋 

from https://se.ewi.tudelft.nl/events/2020/05/07/reading-club-literature-surveys/ I understood that you are now hosting the reading club publicly online, and if so, I would be very happy to join.

If you think that might be possible, would you be so kind to please share the Zoom URL as well? Thanks!

**Comment by lacinoire** [comment]
Hey 😃 cool that you want to join 😊

We're afraid about Zoom-Bombing so therefore don't want to post any Zoom Link publicly :)

Would you send me an e-mail (c.e.brandt _at_ tudelft.nl)? then I'll give you the zoom link!

**Comment by lacinoire** [comment]
I've added a note to the event as well 🙂

**Comment by bzz** [comment]
Hey, thanks for the prompt response! Makes perfect sense, just did that.
